## DENGUI PREDICTION WITH DIFFERENT MODELS

In [95]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn import datasets, linear_model
from sklearn.metrics import mean_absolute_error

### DataSets

In [96]:
x_train = pd.read_csv(r'E:\uni\tools and techniques\Project\dengue_features_train.csv')


In [97]:
y_train = pd.read_csv(r'E:\uni\tools and techniques\Project\dengue_labels_train.csv')

In [98]:
x_test = pd.read_csv(r'E:\uni\tools and techniques\Project\dengue_features_test.csv')

In [99]:
x_train.shape


(1456, 24)

In [100]:
y_train.shape

(1456, 4)

### Check whether dataset contain null value or not

In [101]:
x_train.columns[x_train.isnull().any()].tolist()

['ndvi_ne',
 'ndvi_nw',
 'ndvi_se',
 'ndvi_sw',
 'precipitation_amt_mm',
 'reanalysis_air_temp_k',
 'reanalysis_avg_temp_k',
 'reanalysis_dew_point_temp_k',
 'reanalysis_max_air_temp_k',
 'reanalysis_min_air_temp_k',
 'reanalysis_precip_amt_kg_per_m2',
 'reanalysis_relative_humidity_percent',
 'reanalysis_sat_precip_amt_mm',
 'reanalysis_specific_humidity_g_per_kg',
 'reanalysis_tdtr_k',
 'station_avg_temp_c',
 'station_diur_temp_rng_c',
 'station_max_temp_c',
 'station_min_temp_c',
 'station_precip_mm']

In [102]:
x_train.columns[x_train.isnull().any()].tolist()



['ndvi_ne',
 'ndvi_nw',
 'ndvi_se',
 'ndvi_sw',
 'precipitation_amt_mm',
 'reanalysis_air_temp_k',
 'reanalysis_avg_temp_k',
 'reanalysis_dew_point_temp_k',
 'reanalysis_max_air_temp_k',
 'reanalysis_min_air_temp_k',
 'reanalysis_precip_amt_kg_per_m2',
 'reanalysis_relative_humidity_percent',
 'reanalysis_sat_precip_amt_mm',
 'reanalysis_specific_humidity_g_per_kg',
 'reanalysis_tdtr_k',
 'station_avg_temp_c',
 'station_diur_temp_rng_c',
 'station_max_temp_c',
 'station_min_temp_c',
 'station_precip_mm']

In [103]:
x_test.columns[x_test.isnull().any()].tolist()

['ndvi_ne',
 'ndvi_nw',
 'ndvi_se',
 'ndvi_sw',
 'precipitation_amt_mm',
 'reanalysis_air_temp_k',
 'reanalysis_avg_temp_k',
 'reanalysis_dew_point_temp_k',
 'reanalysis_max_air_temp_k',
 'reanalysis_min_air_temp_k',
 'reanalysis_precip_amt_kg_per_m2',
 'reanalysis_relative_humidity_percent',
 'reanalysis_sat_precip_amt_mm',
 'reanalysis_specific_humidity_g_per_kg',
 'reanalysis_tdtr_k',
 'station_avg_temp_c',
 'station_diur_temp_rng_c',
 'station_max_temp_c',
 'station_min_temp_c',
 'station_precip_mm']

In [104]:
y_train.columns[y_train.isnull().any()].tolist()

[]

### Now fill null values with mean of than column

In [105]:
x_train = x_train.fillna(x_train.mean())

In [106]:
x_train.columns[x_train.isnull().any()].tolist()

[]

In [107]:
x_test = x_test.fillna(x_test.mean())

In [108]:
x_test.columns[x_test.isnull().any()].tolist()

[]

In [109]:
y_train = y_train.fillna(y_train.mean())

### Check the shape of datasets

In [110]:
x_test.shape

(416, 24)

In [111]:
x_train.shape

(1456, 24)

In [112]:
y_train.shape

(1456, 4)

In [113]:
y_train = y_train['total_cases']

In [114]:
y_train.shape

(1456,)

### Columns which are category type convert it into numeric form

In [115]:
x_train['city'] = x_train['city'].astype('category')
x_train['city'] = x_train['city'].cat.codes

In [116]:
x_test['week_start_date'] = x_test['week_start_date'].astype('category')
x_test['week_start_date'] = x_test['week_start_date'].cat.codes

In [117]:
x_test['city'] = x_test['city'].astype('category')
x_test['city'] = x_test['city'].cat.codes

In [118]:
x_train['week_start_date'] = x_train['week_start_date'].astype('category')
x_train['week_start_date'] = x_train['week_start_date'].cat.codes

In [119]:
x_test.head()

city  year  weekofyear  week_start_date  ndvi_ne   ndvi_nw   ndvi_se  \
0     1  2008          18                0 -0.01890 -0.018900  0.102729   
1     1  2008          19                1 -0.01800 -0.012400  0.082043   
2     1  2008          20                2 -0.00150  0.126803  0.151083   
3     1  2008          21                3  0.12605 -0.019867  0.124329   
4     1  2008          22                4  0.05680  0.039833  0.062267   

    ndvi_sw  precipitation_amt_mm  reanalysis_air_temp_k        ...          \
0  0.091200                 78.60             298.492857        ...           
1  0.072314                 12.56             298.475714        ...           
2  0.091529                  3.66             299.455714        ...           
3  0.125686                  0.00             299.690000        ...           
4  0.075914                  0.76             299.780000        ...           

   reanalysis_precip_amt_kg_per_m2  reanalysis_relative_humidity_percent  \
0                            25.37                             78.781429   
1                            21.83                             78.230000   
2                             4.12                             78.270000   
3                             2.20                             73.015714   
4                             4.36                             74.084286   

   reanalysis_sat_precip_amt_mm  reanalysis_specific_humidity_g_per_kg  \
0                         78.60                              15.918571   
1                         12.56                              15.791429   
2                          3.66                              16.674286   
3                          0.00                              15.775714   
4                          0.76                              16.137143   

   reanalysis_tdtr_k  station_avg_temp_c  station_diur_temp_rng_c  \
0           3.128571           26.528571                 7.057143   
1           2.571429           26.071429                 5.557143   
2           4.428571           27.928571                 7.785714   
3           4.342857           28.057143                 6.271429   
4           3.542857           27.614286                 7.085714   

   station_max_temp_c  station_min_temp_c  station_precip_mm  
0                33.3                21.7               75.2  
1                30.0                22.2               34.3  
2                32.8                22.8                3.0  
3                33.3                24.4                0.3  
4                33.3                23.3               84.1  

[5 rows x 24 columns]

### Scaled the data to check if it gives accuracy or not

In [157]:
from sklearn import preprocessing
standardize_x_train = preprocessing.scale(x_train)

C:\Users\Fatima\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int8, int16, int64, float64 were all converted to float64 by the scale function.
  


In [158]:
standardize_x_test = preprocessing.scale(x_test)

C:\Users\Fatima\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int8, int16, int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


### Import the file where we have to replace our predicted values

In [153]:
testFile = pd.read_csv(r'E:\uni\tools and techniques\Project\submission_format.csv')

In [154]:
testFile.head()

city  year  weekofyear  total_cases
0   sj  2008          18            4
1   sj  2008          19            4
2   sj  2008          20            4
3   sj  2008          21            6
4   sj  2008          22            3

## GRADIENT DESCENT CLASSIFIER

#### With standardize datasets

In [173]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(n_estimators=30, max_depth = 10, random_state = 1)
gbc.fit(standardize_x_train,y_train)
y_predict = gbc.predict(standardize_x_test)
y_predict = y_predict.astype('int64')
testFile['total_cases'] = y_predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
y_predict

array([ 37,  31,  18,   3,  53,  19,   8,  18,  12, 128,   6,  28,  13,
        13,  23,  21,  44,  21,  23,  16,  71,  66,  23,  71, 129,   8,
        56,  23,  65,   9,  26,  20,  17,  19,  27,   9,  26,  50,  38,
         7,  18,  20,  11,  11,  11,  23,   8,   2,  20,  18,  75,  37,
        18,  19,  12,   8,  18,  48,  20,  20,  21,   7,  14,   8,   4,
         4,  19,  13,  11,   5,  20,   4,  14,  11,  30, 101,   2,  31,
        14,  16,  26,  20,  11,  11,  23,  22,  20,  59,  50,   4,   7,
        16,  29,   7,  14,  75,  19,  43,  31,  16,  14,   6,  11,   4,
        31,  31,  35,  21,  11,   7,   7,  64,  10,  75,  28,  14,  16,
        99,  28,  33,   6,   2,  14,   2,  20,  21,   4,  11,  17,  54,
        17,  16,  30,  30,  13,  29,  24,  11,   9,  20,  12,  75,  14,
        37,   8,   0,   0,   4,  14,  20,  16,  15,   4,  20,  15,  11,
        20,  11,  11,  43,  25,  14,   7,   7,  27,   7,   7,  11,   7,
         7,   7,   7, 127,   7,   7,  27,   7,   7,  25, 102,   

#### Without standardize datasets

In [120]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(n_estimators=30, max_depth = 10, random_state = 1)
gbc.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=10,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=30,
              n_iter_no_change=None, presort='auto', random_state=1,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [121]:
y_predict = gbc.predict(x_test)

In [92]:
y_predict

array([129,   5, 129,   3,   6,  12,   8,  12,   2,   8,   8,  28,  54,
        23,  23,  21,  21,  21,  23,  68,  68,  17,  17,  52,   2,  52,
        57,  52,  53,  56,  53,  34, 108, 108,  27,  24,  17,  23,   4,
         7,  23,  15,  12,   9,  11,   1,  17,  24,  11,  17,  15,  37,
         8,  24,  12,   4,  10,  15,  21,  11,  24,  23,  23,  12,  23,
        33,  23,  23,  23,  66,  40,  12,  21,  23,  24,  23,  40,  23,
        31,   5,  36,  21,  48,  10, 108,  22,  21,  24,  11,  18,  12,
         8,  20,  26,  38,  18,  33,  72,  31,  11,  34,   7,  31,  18,
        11,  23,  15,  26,  23,  10,  23,  28,   3,  22,  23,  23,  30,
        17,  23,  23,  23,  19,  18,  24,  23,  21,  71,  23,  71,  17,
        71,   3,  29,  11,   3,  60,  53,   3,  17,  47,  12,  75,  14,
        14,  34,  16,  36,  18,  27,  24,   3,  11,  31,  18,   2,   8,
         6,  10,  11,  11,  11,  12,  11,  19,   6,   6,  99,  15,  11,
        23, 127,  15,  10,  19,  31,  27,  15,   2,  25,  17,  1

#### Without standardize datasets with increased hyperparameters

In [188]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(n_estimators=32, max_depth = 15, random_state = 1)
gbc.fit(x_train,y_train)
y_predict = gbc.predict(x_test)
testFile['total_cases'] = y_predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
y_predict

array([129,   5,  19,   3,   6,  12,   6,   6,  14,   6,  18,  11,   2,
         5,  13,  14,  12,  13,  23,   2,  13,  17,  17,   4,   4,  12,
        57,   3,   9,  56,  47,  34,  17, 108,  14,  31,  17,  33,  12,
         7, 142,   6,  29,   5,  11,   5,   5,   8,  29,  16,  17,  16,
         8,   2,  30,  30,  10,  15,  21,   5, 142,   5,   5,  12,  17,
        61,   5,  55,  23,   5,  31,  12,  20,  92,   4,  23,   3,  22,
         5,   5,  36,  18, 169,  19, 108,  33,  12, 112,  11,   6,   1,
         6,  20,  11,  16,   4,   5,   0,  36,  10,   4,   6,  31,   2,
        12,  53,   0,  20,  21,  17,  10,  30,  10,  14,   7,  23,  16,
        17,   5,   4,  18,   3,  12,  14,  15,   4,   5,  23,   5,  33,
        30,   3,  17,  12,   3,  60,  21,   3,  17, 112,  12,  33,  14,
        14,  31,  11,   9,   6,  11,  22,   8,  11,   4,   0,   9,   6,
        11,  10,  11,  10,  12,  12,  25,  17,  10,  10,   4,  15,  13,
        26,  20,  15,  10,  10,  31,  10,  10,  17,  30,  30,  1

#### Without standardize datasets with increased hyperparameters

In [190]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(n_estimators=50,max_depth =25 , random_state = 0)
gbc.fit(x_train,y_train)
y_predict = gbc.predict(x_test)
testFile['total_cases'] = y_predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
y_predict

array([  5,   5,   3,   3,   6,   6,   6,   6,   6,   6,  18,   6,   2,
         5,  13,  31,  12,  15,  23,   2,  13,  18,  17,  52,   0,  12,
        52,   3,  53,  56,  53, 142,  17,  33,  14,  21,  17,   0,  33,
         7, 142,   0,  29,   0,   7,   5,  25,   8,   6, 142,  11,  37,
         0,  12,   4,  30,   4,  15,  21,   5,  14,   5,   5,  12,  17,
        33,   5,  55,  16,   5,  40,  12,   9,   5,  23,   4,   3,  30,
         5,   5,  36,  16,  48,  19,  17,  22,  17,  30,   4,   0,   1,
        10,  20,   7,  16,   0,  16,   0,  31,   9,   4,   4,   0,   0,
         3,  53,   0,  21,  21,   7,  10,   4,   3,   6,   7,   4,  12,
        17,   5,   5,  18,  26,   9,   2,  15,  42,  71,  23,   2,  33,
         3,   3,  17,   3,   3,  60,  47,   3,  17,  29,   5,  75,  14,
        31,  31,   0,   9,  13,   2,  36,   2,   0,  31,   0,   0,   0,
         6,   6,   4,  10,  31,   4,   2,   1,   5,   6,  12,   6,  68,
        27,  48,  15,  34,   1,  26,  10,   4,  17,  25,  10,  1

In [122]:
y_predict.shape

(416,)

## RANDOM FOREST CLASSIFIER

#### Without standardize datasets

In [128]:
from sklearn.ensemble import RandomForestClassifier

In [132]:
regr = RandomForestClassifier(max_depth=20, random_state=0,n_estimators=100)

In [133]:
regr.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=20, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [134]:
predict = regr.predict(x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
predict

array([  3,   4,   1,   3,  17,   4,   4,   5,   6,   6,   2,   2,  14,
         5,  27,  14,  27,  21,  42,  20,   7,   4,  14,   6,  33,  26,
        13,  30,   6,   6,  23,   3,   8,   8,  27,  81,   9,  26,  17,
        17,  17,  20,   4,  17,   3,   7,  17,   1,   3,   3,  17,   3,
        17,   3,   3,  17,   2,   6,   7,  20,  16,   9,  14,  14,  14,
        11,  60,  14,  14,  24,  13,   9,   7,  14,  14,  25,  24,  35,
        13,   6,   6,  18,   2,   8,  30,  40,  17,  30,  10,   7,  10,
        17,   9,  14,  17,   3,   4,   7,  11,   8,   2,   6,  17,  13,
        16,  13,   2,   6,  14,  23,  11,  14,  18,  16,  21,  35,  11,
        23,  14,  24,  75,  24,  24,   4,  21,  42,  20,  31,  42,   6,
         9,   5,  34,  12,  13,   6,   3,   6,  17,  17,  15,  10,  22,
        14,  14,  17,  17,  17,   6,   7,   2,   3,  11,   7,   3,   8,
         5,  17,   3,   4,  23,   7,   3,  14,  59,   4,  14,   4,   7,
        18,  18,  26,  27,  42,   2,   7,  42,  30,  27,   6,  2

#### Without standardize dataset with increased hyperparameters

In [136]:
regr = RandomForestClassifier(max_depth=30, random_state=0,n_estimators=130)
regr.fit(x_train,y_train)
predict = regr.predict(x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
predict

array([  4,   4,   4,   3,   3,  16,   4,   5,   2,   6,  25,  28,   2,
         5,  27,  28,   2,  21,  31,  20,  14,  30,   2, 112,  33,  26,
         2,  30,   2,  30,  29,   7,  15,  17,  17,  81,   7,  26,   7,
         7,   6,  20,   6,   3,   6,   3,   2,   3,   2,   6,   3,   6,
         8,   3,   3,   3,   2,   6,   6,  14,  14,  31,   7,  14,  14,
         7,  16,   7,  31,  24,  40, 127,  40,  20,  33,  33,   2,  35,
        13,  68,  48,  20,  29,   2,  48,   3,  17,  59,  17,   6,  10,
         7,   9,   9,   8,   6,   5,   7,   7,   8,   7,   7,   7,   2,
        16,  13,   6,   6,   3,  23,   5,   2,  23,   3,  21,  10,  23,
        23,  17,  31,  31,  19,  31,  31,  27,  73, 127,  31,   2,  65,
        13,   2,  34,  12,  29,  13,   3,   6,  17,  17,  28,  16,  22,
        17,  17,   7,   6,   6,   2,   6,   2,   3,   5,   2,   7,  16,
         3,   3,   3,   3,   3,   3,   3,  19,   6,  18,  16,   3,  11,
        25,  18,  16,   6, 204,  25,  27,  73,  25,  27,   6,  2

#### With standardize dataset

In [183]:
regr = RandomForestClassifier(max_depth=30, random_state=0,n_estimators=100)
regr.fit(standardize_x_train,y_train)
predict = regr.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)  //29.4094

[  4   4   4   4   4   4   6  18  14  14   6  31  28  17  23  12  28  21
  31  20  14  17  26 129 140 116  43  30 140 116  28  27  17  17  27  81
  13  17   6  26  37  26  23  18  23  23  23  12  21  24   5   6  17  31
  17  17  22  31  31  16  89  31  11  31  25   9  25  89  23  31  40 127
  40  14  31  31  42  31   9  89  17  36  36  31  17   4  17  59  17  17
  17  14  31  14  17  75   4   5  37   8   8   8  15  14   7  48   7   6
   7  23  11 128  14 102  42  59   7 191  25  31 329  31  24  24  48  21
  73  56  68  24  89  30  24  30  30  17  27  30  17  17  12   7   7   7
  14  13   6  18   6   6   3   3   7  11   6  12   7   7   3   1   3  10
   3   4   1   3  10   5   7  18   7  26   6   4   7   4   7   7   9   6
  20   5  10   9   7  13  29  15   6   6   6   8   7   8  10  20   7  11
   3   7   7   3   3   3   3   3   7  19   3   7   3  10   2   7  13  10
  26  11  13   4  14   7  13  10   7   7  18  11  13  34  33   4  16   4
  10  17  13  10   7  26  22  12  17   6  10   1   

In [147]:
regr = RandomForestClassifier(max_depth=50, random_state=0,n_estimators=100)
regr.fit(x_train,y_train)
predict = ct(x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

array([  3,   4,   4,   4,   6,   3,   5,   5,   6,   6,   6,   2,   6,
         5,  23,  14,  21,  38,  33,  20,   2,  14,   5,   2,   2,  21,
         3,   3,   2,  17,  17,  17,  22,   6,  12,  81,   9,   7,   7,
         6,  17,  17,   6,   9,   3,   3,  20,  18,  17,   3,   3,   6,
         6,   3,   3,   3,   2,   5,   0,   3,   2,  13,  14,   9,   6,
        14,   5,   9,  27,  24,  55,  38,   9,  20,  73,  31,  31,  35,
        13,   2,  48,  20,  29,   0,  68,  49,  17,  59,  17,   7,  10,
        17,   9,  17,  12,   7,   7,  18,  11,  10,   7,   6,   6,   2,
         3,   5,   7,   6,  20,  23,   5,  12,  17,   5,  21,  10,  23,
        23,  14,  19,  31,  24,   4,  15,  16,   4, 127,  26,  20,  65,
        13,   0,  23,  29,  29,  17,  18,  26,  17,  17,   8,   7,  14,
        17,  17,   7,  17,   6,   2,   9,   6,   6,   5,   2,   7,  14,
         2,   3,   3,  10,   3,   3,   3,  19,  10,   4,  11,  21,   6,
        10,  25,  26,   6,  26,  26,  27,  10,  25,  14,   6,   

## RANDOM FOREST REGRESSOR

#### With standardize datasets

In [186]:
 from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(max_depth=30, random_state=0,n_estimators=100)
regr.fit(standardize_x_train,y_train)
predict = regr.predict(standardize_x_test)
predict = predict.astype('int64')
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[ 10  11  11  12  11  11  11  21  15  15  19  21  29  52  47  95  62 119
 171  71  76  74  93 107 104  85  90  92 100  84  78  97  83  81  92  60
  49  41  38  40  31  25  24  31  28  22  23  21  22  21  17  18  20  21
  19  21  20  21  30  41  50  56  72  69  84  91  90  78  79 106 163  44
  66  57 120 124 125  60 104  69  54  65 103  62  43  68  49  74  43  51
  41  40  40  44  37  34  34  29  24  27  24  26  23  33  48  54  43  47
  47  54  61  62  87 101 119 129 125 137 141 195 163 149  78  54  49  63
  39  43  53  41  39  43  32  28  23  24  31  23  19  25  14  13  17  21
  17  14  14  13  12   7   7   7   7   5   5   8   6   6   7   6   8  12
  13  18  23  18  17  17  18  26  20  25  18  22  25  15  17  22  25  27
  21  17  20  28  22  23  23  26  17  24  18  18  14  12  14  10  11  12
   9  11   8   4   6   5   5   4   5   6   4   8   5  12   6   6  10   9
  21  19  15  15  13  18  16  23  26  20  16  17  28  27  30  30  22  38
  43  80  47  29  46  22  21  20  18  10  14  10  1

## DECISION TREE CLASSIFIER

#### Without standardize datasets

In [145]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 15)
clf.fit(x_train,y_train)
clf.predict(x_test)

array([  5,   5,   5,   5,   5,   5,   5,   5,   8,   8,  29,  17,   6,
         8, 329,  76,  21,  21,  31,  29,  20,  20,  32,  20,  29,  20,
        20,  32,  20,  20,  20, 141,  25,  17,  27,  81,  13,  46,  22,
        46,  35,  26,  22,  26,  23,  10,  17,   8,  17,  17,  17,   8,
         8,   8,  10,  10,  18,  24,  18,  18,  14,  16,  14,   6,  24,
        13, 329,  76,  21,  24,  40,  20,  20,  30,  24,  31,  31,  46,
       140, 140,  34,  34,  36,  76,  36, 129,  46,  59,  65,  22, 104,
        22,  35,  17,  81,  35,  22,  37,  24,   6,  16,   6,  24,  13,
        18,   6,  24,  13,  14,  18,  14,  17,  20,  20,  24,  14,  18,
        17,  17,  19,  76,  24,  24,  24,  27,  27,  36,  36,  29,  29,
        36,  32,  34,  32,  46,  17,  26,  32,  47,  29,  28, 104,  13,
        31,  31,  35,  22,  31,  36,   6,  29,  59,   6,  14,   6,  16,
         6,  10,  26,  28,  23,  20,  17,  19,  14,  14,  14,  13,  18,
        14,  14,  26,  21,  76,  26,  27,  27,  36,  27,  27,  2

#### Without standardize datasets with increased hyperparameters

In [146]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 35)
clf.fit(x_train,y_train)
predict = clf.predict(x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

array([  5,   5,   7,   5,   5,   5,   5,   7,   5,   7,  16,  16,  16,
         5,  23,  76,  23,  23,  33,  61,  89,  43,  31,  20,  61,  43,
        43,  43,  43,  43,  43,  53,  29,  17,  27,  81,  56,  21,  31,
        21,  35,  26,  55,  26,   5,   6,  16,  16,   7,   5,   5,   5,
         5,   5,   6,   6,   2,  16,   5,   5,  15,  16,   7,  15,  16,
         2, 179,  60,  60,  24,  40,  68,  68,  31,  40,  33,  33,  64,
       142, 140,  80,  80, 112,  76,  28,  76,  64,  59,  65,  90, 104,
        39,  35,  17,  81,  35,  39,  37,  16,  16,  16,  16,   5,   4,
         5,  16,  16,   2,  15,   2,   5,  15,   5,   5,  16,   8,   5,
         5,  16,  76,  76,  40,  40,  40,  56,  73,  36,  36,  61,  61,
        28,  32,  34,  89,  43,  17,  26,  43,  47,  53,  28,  37,  56,
        38,  55,  35,  39,  38,  65,   5,  16,   2,  16,   4,   5,   6,
         5,   6,   6,  11,  11,   2,   6,   2,  16,   3,   6,   6,  16,
         5,  16,  13,  19, 204,  26,  73,  56,  28,  27,  56,  7

#### With standardize datasets

In [174]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 25)
clf.fit(standardize_x_train,y_train)
predict = clf.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[  5   5   5   5   5   5  20  18  10  10  29  17   2  10  44 220  44 220
  89  92  43  43  89 116 129  36  74  30  61  28  36  53  29  17  27  81
  56  21  31  39  35  38  55  26  23  23  24  24  18  13  13  24  24   6
  10  10  20  21  31  38  38  16  55  80  49  55  19  19  44  21  31  74
  34 202  53  31  31  43  19  19  80  80  80  56  19  56  30  59  50  17
  49  56  17  31  17  50  56  37   3   8   8   3  10   4  16  71  36  36
  71  32  48  48  44 127  51  48  11 191  48 220 329  21  24  24  80  80
 127  48  29  76  42  32  17  17   6   3   2   0   1   3   6  10   7  14
  20  20  20  20  12   5  12   6   4   8   8   4   8   8   6   4   3   3
   3  18   1   2   7   7   7   7   7   7   7   7   3   7   7   7   7  25
  39  39  34  34  30  34  34  37  12  13  13  13  10   1   8   9  20  19
   6  11   6  10   7   3   3   3   7   3   3   7   3  10  10   7  10  10
  34  14  14   4   6   6  33  14  14  10  14  11  36  11  14  17  20  10
  14  14  20  21  20  20  22  17  13   6  26   7   

#### With standardize datasets with increased hyperparameter

In [175]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 32)
clf.fit(standardize_x_train,y_train)
predict = clf.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[  5   5   5   5   5   5  20  18  10  10  29  17   2  10  60  76  60  60
  68  92  89  43  30 116  56  36  36  30  36  36  36  53  25  17  27  81
  56  21  31  39  35  38  55  26  23  23  24  24  18  13  13  24  24   6
  10  10  20  21  31  38  38  16  55  80  49  55 115 115  19  17  31 202
  34  61  53  33  31  30  19  19  24  80  24  76  34  31  46  59  50  17
  49  56  17  31  17  50  56  37   3   8   8   3  10   4  16  71  36  36
  71  32 128  59  44 127  51  48  11 191  59  76  76 263  40  40  80  80
 127  48  33  33  42  32  17  17   6   3   2   1   0   3   5  10   7  14
  20  20  20  20  18   5  18   6   4   8   8   4   8   8   4  19   4   3
   3  18   1   1   4   4   4   4  10  10   7  10   3   7   7  10  10  56
  39  31  17  31  30  34  31  26  19  19  13  13  22   8   6   9  20   9
   6  11   6  10   7   3   3   3   7   3   3   7   2   1  10   7  10  11
  17  14  14   4  12  12  16  14  14  19  14  11  36  11  14  17  40  15
  14  14  20  21  40  10  26  19  17   6  22   7   

In [176]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 40)
clf.fit(standardize_x_train,y_train)
predict = clf.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict) // 28.5938

[  5   5   5   5   5   5  20  18  10  10  29  17   2  10  60  76  60  60
  68  92  89  43  30 116  92  36  36  30  36  36  36  53  25  17  27  81
  56  21  31  39  35  38  55  26  23  23  24  24  18  13  13  24  24   6
  10  10  20  21  31  38  38  16  55  80  49  55 115 115  19  17  33 202
  34  61  53  33  33  30  19  19  80  80  80  31  34  31  46  59  50  17
  49  56  17  31  17  50  56  37   3   8   8   3  10   4  16  71  36  36
  71  32 128  59  44 127  51  48  11 191  59  76  76 263  40  40  80  80
 127  48  61  61  42  32  17  17   6   3   2   0   0   3   6  10   7  14
  28  28  20  28  12   5  12   6   4   8   8   4   8   8   4   4   3   3
   3  16   2   2   7   7   7   7   7   7   7   7   3   7   7   7   7  25
  39  31  18  18  30  34  18  37  12  12  13  13  26   1   8  17  20  19
   6  11   8  10   7   3   3   3   7   3   3   7   3   1  10   7  11  10
  17  14  14  20  45  20  16  14  14  92  29  11  75  11  14  25  23  15
  14  14  20  14   4  10  26  29  13  12  26   7  1

In [177]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 100)
clf.fit(standardize_x_train,y_train)
predict = clf.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[  5   5   5   5   5   5  20  18  10  10  29  17   2  10  60  76  60  60
  68  92  89  43  30 116  92  36  36  30  36  36  36  53  25  17  27  81
  56  21  31  39  35  38  55  26  23  23  24  24  18  13  13  24  24   6
  10  10  20  21  31  38  38  16  55  80  49  55 115 115  19  17  33 202
  34  61  53  33  33  30  19  19  80  80  80  31  34  31  46  59  50  17
  49  56  17  31  17  50  56  37   3   8   8   3  10   4  16  71  36  36
  71  32 128  59  44 127  51  48  11 191  59  76  76 263  40  40  80  80
 127  48  61  61  42  32  17  17   6   3   2   0   0   3   6  10   7  14
  28  28  20  28  12   5  12   6   4   8   8   4   8   8   4   4   3   3
   3  16   2   2   7   7   7   7   7   7   7   7   3   7   7   7   7  25
  39  31  18  18  30  34  18  37  12  12  13  13  26   1   8  17  20  19
   6  11   8  10   7   3   3   3   7   3   3   7   3   1  10   7  11  10
  17  14  14  20  45  20  16  14  14  92  29  11  75  11  14  25  23  15
  14  14  20  14   4  10  26  29  13  12  26   7  1

## DECISION TREE REGRESSOR

#### With standardize datasets

In [191]:
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor(random_state=0,max_depth = 100)
clf.fit(standardize_x_train,y_train)
predict = clf.predict(standardize_x_test)
predict = predict.astype('int64')
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict) ##28.5938

[ 10   4  10   6  10   4   4  18  17  14  17  21  17  14  64 142  92  60
  76  92  25  52 179 140 140 140 116 140 140 129  47 108  89  44  74  81
  37  31  35  31  26  20  33  59  59  21  16  16  21  24  13  24  25  17
  22  22  22  19  31  17  49  55  49  55  84  84 154 202 202 154  31  19
  31  33  19  47  42  25  34  21  21  36  59  23  21  24  19  59  50  63
 104  65  35  53  29  26  32  34  26  26  26  26  32  34  26  26  26  44
  44  46  51  44 102  71 128 127 150 256 128 181 329 179  30  13  56  14
   8  61  61  65   9  55   9   9   9  17  16   9   9  35  16  16  11  28
  20  18  13  17   3   3   3   6   3   7   7  12   7  10   3  10   5  10
   5  16   4   6   8  10   4   6   6  25   2  16   3   3  56  14   4  56
  22  22   7  16  22  12   4  15  19  19  12  34  15  15  15  17  17  17
  15  21  15   1   4   2   3   3   7   6   3  10   3  10  10   5  11  10
  10   6   4  13   2   7   5   6  43  56  14  10  34  34  16  43  20  20
   7 170  21  10  20  29  26  13  29   8   8   8   

## ADABOOST CLASSIFIER

#### Without standardize datasets

In [143]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=10, random_state=1)
abc.fit(x_train, y_train)
predict = abc.predict(x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

array([  6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,  15,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   0,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6, 106, 106,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,  73,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   

#### With standardize datasets

In [182]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=30, random_state=1)
abc.fit(standardize_x_train, y_train)
predict = abc.predict(standardize_x_test)
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[ 6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6 23  6  6
  6  6  6  6  6  6 73 23  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  0  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6 73  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6 23  6  6  6 23 23  6  6  6 23 23
  6  6  6  6  6 23  6  6  6  6  6  6  6  6  6  6  6  6  6  6 23 73  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6 23  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6 23  6  6  6  6  6  6  6  6  6  6  6  6  6  6  0  0  0  0
  0  0  0  0  0  6  0  0  0  0 82  0  0  6  6  0  0  6  6  6  6  6  6  0
  6  0  0  0  0  6  0  6  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6

## KNEIGHBORS REGRESSOR

#### Without standardize datasets

In [167]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
linearRegression = KNeighborsRegressor(n_neighbors=12)
linearRegression.fit(x_train,y_train)
predict = linearRegression.predict(x_test)
predict = predict.astype('int64')
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict)

[ 19   7  13  18  13  21  20  22  11  22  13  22  17  23  23  20  21  23
  23  42  23  50  23  23  23  44  25  24  30  27  29  26  30  29  34  17
  21  21  18  22  21  14  18  21  47  17  22  19  21  21  20  18  17  17
  27  66  56  27  29  36  41  30  40  44  52  43  54  48  44  68  61  70
  62  54  48  57  74  77  70  76  57  53  41  69  73  72  70  64  47  42
  43  46  46  46  46  41  46  65  61  46  46  40  46  59  43  41  48  57
  44  28  43  45  43  35  70  44  31  46  40  49  42  43  43  40  35  39
  43  51  36  37  31  40  33  38  33  30  30  42  41  31  16  17  17  18
  18  18  17  17  16  15  18  18  15  17  17  15  17  26  13  48  48  37
  25  45  24  40  34  18  27  32  27  34  22  24  24  21  25  60  29  29
  40  27  34  29  85  35  29  31  92  46  29  39  27  28  27  29  27  27
  26  28  27  24  26 113  66 166  33 150  25  29 169  70  60  37  70  70
  59  70  78 181  99 199 122 186 184  84 173 123 117 132 125 171 151 252
 198 139 142 186 114 221 157 135 169  46  27  28  2

#### With standardize datasets

In [181]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
linearRegression = KNeighborsRegressor(n_neighbors=15)
linearRegression.fit(standardize_x_train,y_train)
predict = linearRegression.predict(standardize_x_test)
predict = predict.astype('int64')
testFile['total_cases'] = predict
export_excel = testFile.to_csv(r'E:\uni\tools and techniques\Project\submission_format.csv',index=None,header=True)
print(predict) // 29.3293

[ 18  19  16  28  22  37  21  31  41  41  38  59  22  44  72  46  59  41
  50  57  72  51 107  65 124  64  79  49  93 116 117  49  69  75  42  22
  26  27  21  25  22  19  22  23  20  24  25  27  24  18  21  18  21  23
  17  19  40  29  23  27  40  56  45  41  59  43  77  56  64  71  41  58
  48  79  94  79  56  40 135  79  70  44 126 115  45  95  65 136  28  26
  17  26  22  24  21  20  16  18  27  11  15  19  18  15  22  17  13  29
  14  50  84  34  52  56  83  98  50  38  56  69  59  87  56  54  43  47
  35  35  44  26  36  39  60  31  17  26  22  28  21  22  17  23  16  18
  19  17  18  21  20  16  19  14  16  17  13  12  12   8  10  21  28  31
  14  45  17  29  27  14  30  24  25  35  23  47  63  19  45  30  40  34
  23  20  18  26  31  24  30  28  15  27  19  21  16  14  11  11  11  13
   6  11  10  11   9   9  12   7   8   8   9   9   4   9   6   9  22  24
  32  26  16  34  28  21  21  27  46  32  42  36  45  43  36  44  29  28
  34  33  40  27  16  19  23  16  19   9   9   5   

#### the End